FROM node:10.13.0-alpine

LABEL maintainer="Donald Richardson <me@donaldrichardson.net>" \
      org.label-schema.vendor="Strapi" \
      org.label-schema.name="Strapi Docker image" \
      org.label-schema.description="Strapi containerized" \
      org.label-schema.url="https://strapi.io" \
      org.label-schema.vcs-url="https://github.com/donaldr/strapi-docker" \
      org.label-schema.version=latest \
      org.label-schema.schema-version="1.0"

RUN apk add git
RUN apk add vim

RUN apk --update --no-cache \
                add  \
                automake \
                bash \
                git \
                alpine-sdk  \
                nasm  \
                autoconf  \
                build-base \
                zlib \
                zlib-dev \
                libpng \
                libpng-dev\
                libwebp \
                libwebp-dev \
                libjpeg-turbo \
                libjpeg-turbo-dev

RUN mkdir /usr/local/lib/strapi
WORKDIR /usr/src/api

RUN echo "unsafe-perm = true" >> ~/.npmrc

EXPOSE 1337

COPY healthcheck.js ./
HEALTHCHECK --interval=15s --timeout=5s --start-period=30s \
      CMD node /usr/src/api/healthcheck.js

CMD ["tail", "-f", "/dev/null"]
